repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.6.0
    hooks:
    -   id: pyproject-fmt
        args: [
            "--indent", "4",
            "--keep-full-version",
            "--max-supported-python", "3.13",
        ]

# Inspired from https://til.unessa.net/git/pre-commit-hook/
-   repo: local
    hooks:
    -   id: uv-lock-check
        name: uv lock --check
        entry: uv lock --check
        language: system
        files: '^(pyproject.toml|uv.lock)$'
        pass_filenames: false
