name: Verify Hugo

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Install uv & Python
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install Dart Sass
      run: sudo snap install dart-sass

    - name: Checkout
      uses: actions/checkout@v5

    - name: Build with Hugo
      env:
        HUGO_ENVIRONMENT: production  # For backward compatibility with older Hugo modules
        HUGO_ENV: production
      run: |
        uv run hugo \
          --gc \
          --minify \
          --baseURL "${{ steps.pages.outputs.base_url }}/"
